{% set name = "lalxml" %}
{% set version = "1.2.4" %}
{% set sha256 = "5509bcc9cbce0b497036d3fc87628d1cbaa9f33af20cf33609cabd9c6ee398f1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.xz
  url: http://software.ligo.org/lscsoft/source/lalsuite/{{ name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  number: 3
  skip: true  # [win]

requirements:
  build:
    - pkg-config
    - make
    - {{ compiler('c') }}
    - swig>=3.0.7
  host:
    - libxml2
    - lal
    - python
    - numpy
    - python-lal

test:
  imports:
    - lalxml
  commands:
    - lalxml_version --verbose

outputs:
  - name: lalxml
    requirements:
      build:
        - {{ compiler('c') }}
      host:
        - gsl
        - libxml2
        - lal
      run:
        - gsl
        - libxml2
        - lal
    files:
      - bin/lalxml_version
      - etc/lalxml-user-env.*
      - include/lal/LALXML*
      - include/lal/SWIGLALXML*
      - include/lal/swiglalxml*
      - lib/liblalxml*
      - lib/pkgconfig/lalxml*.pc
    test:
      commands:
        - lalxml_version --verbose
    about:
      home: https://wiki.ligo.org/DASWG/LALSuite
      license: GPLv3
      license_family: GPL
      license_file: COPYING
      summary: LSC Algorithm XML Library
      description: |
        The LSC Algorithm XML Library for gravitational wave data analysis.
        This package contains the shared-object libraries needed to run
        applications that use the LAL XML library.
  - name: python-lalxml
    requirements:
      build:
        - {{ compiler('c') }}
        - swig>=3.0.7
      host:
        - {{ pin_subpackage('lalxml', exact=True) }}
        - python
        - numpy
      run:
        - {{ pin_subpackage('lalxml', exact=True) }}
        - python
        - numpy
        - python-lal
    files:
      - lib/python*/site-packages/lalxml/**
    test:
      imports:
        - lalxml
    about:
      home: https://wiki.ligo.org/DASWG/LALSuite
      license: GPLv3
      license_family: GPL
      license_file: COPYING
      summary: LSC Algorithm XML Library
      description: |
        The LSC Algorithm XML Library for gravitational wave data analysis.
        This package contains the python bindings.

about:
  home: https://wiki.ligo.org/DASWG/LALSuite
  license: GPLv3
  license_family: GPL
  summary: LSC Algorithm XML Library

extra:
  recipe-maintainers:
    - duncanmmacleod
    - skymoo
